### ISSUE TITLE
update the router

### ISSUE THREAD

**Issue by Wapweb** [excellalabs/ngComponentRouter#5]
Hello. In the last release of angular https://github.com/angular/angular/blob/master/CHANGELOG.md
they have updated angular1_router

**Comment by duluca** [comment]
Will do tonight

**Comment by duluca** [comment]
I updated the router. Seems like they've fixed all issues, I've been manually changing so far. However, I've noticed this version doesn't just work with Angular 1.5. I've update my test project, http://github.com/duluca/angular1.5-starter, to 1.5.2 and then it worked. I updated the version of the package to 2.0.0 because of that potentially breaking change.

**Comment by Wapweb** [comment]
@duluca thanks
